<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Новости: проекты, организованные молодыми педагогами");
?><p style="text-align:justify;">
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b>29-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1467/">«Главное событие года? Стала учителем гимназии №40!»</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 29-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1466/">«Пять ступеней восхождения к успеху»</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 15-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1441/">Знакомство с группой компаний «Содружество»</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b>15-11-2016 </b><a target="_blank" href="http://gym40.ru/about/events/1444/">Я б работать в порт пошел!</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b>14-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1440/">Форум родительской ученической, педагогической общественности «Роль общественности в оценке качества образования»</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 14-11-2016 </b><a target="_blank" href="http://gym40.ru/about/events/1439/">Интервью-проект в Музее Мирового океана</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 08-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1437/">Конкурс профессиональных навыков «Новые профессии в городе XXI века» &nbsp;как часть программы Международной ассамблеи</a> <br>
<i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b>08-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1436/">V Международная молодёжная ассамблея городов-партнёров Калининграда начала свою работу</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 05-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1434/">V Международная молодёжная ассамблея городов-партнёров Калининграда: «Стратегия восхождения к успеху: молодёжь – образование – профессия – город»</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 02-11-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1432/">Педагогическая ассамблея: пять стратегий успеха</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 31-10-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1431/">Педагогическая ассамблея 2016</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 27-10-2016 </b><a target="_blank" href="http://gym40.ru/about/events/1427/">ФЦПРО 2016-2020 в гимназии. Первые результаты</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 14-10-2016 </b><a target="_blank" href="http://gym40.ru/about/events/1414/">Завершилась XXII сессия Молодёжного Европарламента</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 05-10-2016 </b><a target="_blank" href="http://gym40.ru/about/events/1409/">Открытие XXII сессии Молодежной модели Европарламента</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 05-10-2016 </b><a target="_blank" href="http://gym40.ru/about/events/1408/">Сентябрь – месяц, окрашенный «красками английского языка»</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b>29-09-2016 </b><a target="_blank" href="http://gym40.ru/about/events/1371/">Модель молодежного Европарламента региона Балтийского моря</a><a href="http://gym40.ru/about/events/1371/" style="color: #006699; background-color: #b6e8f7;"></a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b>15-09-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1337/">Общественная кафедра «Образование и дипломатия»: старт в новом учебном году</a> <br>
 <i class="fa fa-newspaper-o fa-lg text-primary" aria-hidden="true"></i> <b> 06-09-2016&nbsp;</b><a target="_blank" href="http://gym40.ru/about/events/1334/">Гости из Чехии в гимназии</a>
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>