<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Методические и организационные документы ");
?><p style="text-align: justify;">
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о рабочих программах_2018.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о рабочих программах в МАОУ гимназия № 40 им. Ю.А. Гагарина</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о режиме занятий обучающихся 2017.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о режиме занятий обучающихся</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Порядок индивид. учета результатов 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок осуществления индивидуального учёта результатов освоения обучающимися образовательных программ и хранения в архивах информации об этих результатах на бумажных и (или) электронных носителях (новая редакция)</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Порядок зачета результатов освоения учащимися учебных предметов 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок зачета результатов освоения учащимися учебных предметов, курсов, дисциплин (модулей), дополнительных образовательных программ в других организациях, осуществляющих образовательную деятельность</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/О формах получения образования 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о формах получения образования, об обучении по индивидуальному учебному плану и ускоренном обучении (новая редакция)</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о правилах внутреннего распорядка 17.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о правилах внутреннего распорядка обучающихся муниципального автономного общеобразовательного учреждения города Калининграда гимназии № 40 имени Ю.А.Гагарина (новая редакция)</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение об использовании цифровых образовательных ресурсов в гимназии.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об использовании цифровых образовательных ресурсов в гимназии</a><br>
 <a href="http://gym40.ru/parents/%D1%84%D0%BE%D1%80%D0%BC%D0%B02.pdf" title="Ссылка: /parents/форма2.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о единых требованиях к одежде обучающихся</a><br>
 
 <a href="http://gym40.ru/Gym40_information/documents/lokalnye/%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%20%D1%83%D1%80%D0%B5%D0%B3%D1%83%D0%BB%D0%B8%D1%80%20%D1%81%D0%BF%D0%BE%D1%80%D0%BE%D0%B2.pdf" title="Ссылка: /Gym40_information/documents/lokalnye/положение по урегулир споров.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о комиссии по урегулированию споров</a><br>
 <a href="http://gym40.ru/Gym40_information/documents/lokalnye/%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6_%D0%BE_%D1%81%D0%BE%D1%86_%D0%BF%D1%81%D0%B8%D1%85_%D1%81%D0%BB%D1%83%D0%B6%D0%B1%D0%B5.pdf" title="Ссылка: /Gym40_information/documents/lokalnye/полож_о_соц_псих_службе.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о социально-психологической службе</a><br>
 <a href="http://gym40.ru/Gym40_information/documents/lokalnye/%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B8%D0%BD%D0%B4%D0%B8%D0%B2%D0%B8%D0%B4%20%D0%BE%D1%82%D0%B1%D0%BE%D1%80.pdf" title="Ссылка: /Gym40_information/documents/lokalnye/положение индивид отбор.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об организации индивидуального отбора обучающихся в классы с углублённым изучением отдельных предметов и профильные классы</a><br>
 <a href="http://gym40.ru/Gym40_information/documents/lokalnye/%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%20%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BA%D0%B5%20%D0%BF%D0%BE%D1%81%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BC%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D0%B9.pdf" title="Ссылка: /Gym40_information/documents/lokalnye/положение о порядке посещения мероприятий.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о порядке посещения мероприятий</a><br>
 <a href="http://gym40.ru/Gym40_information/documents/lokalnye/%D0%9F%D0%BE%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BE%D0%B1_%D0%BE%D0%BA%D0%B0%D0%B7_%D0%BF%D0%BB%D0%B0%D1%82_%D0%B4%D0%BE%D0%BF_%D1%83%D1%81%D0%BB%D1%83%D0%B32015.pdf" title="Ссылка: /Gym40_information/documents/lokalnye/Положение_об_оказ_плат_доп_услуг2015.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об оказании платных дополнительных образовательных услуг</a><br>
 <a href="http://gym40.ru/Gym40_information/documents/lokalnye/%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6-%D0%BE-%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BA%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D0%B0-%D0%BE%D1%82%D1%87%D0%B8%D1%81%D0%BB-%D0%B2%D0%BE%D1%81%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F.pdf" title="Ссылка: /Gym40_information/documents/lokalnye/полож-о-порядке-перевода-отчисл-восстановления.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о переводе, отчислении</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Регламент предоставления услуги Электронный журнал.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Регламент предоставления услуги «Электронный журнал»</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о ведении Электронного журнала.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о ведении электронного классного журнала</a><br>
 <a href="http://gym40.ru/Gym40_information/documents/lokalnye/%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%D1%88%D0%BA%D0%B0%D1%84%D0%B0%D0%BC%D0%B8%20%D0%B4%D0%BB%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%BE%D0%B4%D0%B5%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F.pdf" title="Ссылка: /Gym40_information/documents/lokalnye/правила пользования шкафами для переодевания.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Правила пользования шкафами для переодевания</a>
</p>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>