<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Среднее общее образование");
?><p style="text-align: justify;">
	 <!-- <a href="/Gym40_information/obrazovanie/III-stupen/ООП СОО_2020-2021.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Основная образовательная программа среднего общего образования (ООП СОО)</a><br>
--> <a href="/Gym40_information/obrazovanie/III-stupen/ООП СОО_2022-2024 ФГОС СОО 2012.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Основная образовательная программа среднего общего образования (ООП СОО)</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2022 14:53:17 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a target="_blank" href="/Gym40_information/obrazovanie/III-stupen/УП  СОО_2022-2023.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Учебный план среднего общего образования (из «Организационного раздела» ООП СОО)</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2022 14:42:35 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/fgos/fgos-10-11/programmy/index.php"><i class="fa fa-external-link" aria-hidden="true"></i> Программы учебных предметов, курсов, модулей (приложение к «Содержательному разделу» ООП СОО)</a><br>
 <a href="/fgos/fgos-10-11/programmy-vd/index.php"><i class="fa fa-external-link" aria-hidden="true"></i> Программы курсов внеурочной деятельности (приложение к «Организационному разделу» ООП СОО)</a><br>
 <a target="_blank" href="/Gym40_information/obrazovanie/III-stupen/годовой график СОО 2022-23.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Календарный учебный график среднего общего образования на 2022-2023 учебный год </a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2022 15:31:11 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
</p>
<hr>
<p style="text-align:justify;">
 <a target="_blank" href="/Gym40_information/obrazovanie/III-stupen/ВД СОО 2021.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> План внеурочной деятельности (из "Организационного раздела" ООП СОО)</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2021 13:51:25 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"> <br>
 <a href="/Gym40_information/obrazovanie/I-stupen/Календарный план ВР 2021-2022.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Календарный план воспитательной работы 2021</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2021 14:28:47 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/fgos/fgos-10-11/oipd/oipd.php"><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i> Организация проектно-исследовательской деятельности</a>
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>