<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Документы");
?><p style="text-align: justify;">
 <a target="_blank" href="/about/sport/dokumenty/План работы предметного объединения ф.к. и обж 2022-2023.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> План работы предметного объединения «Физическая культура и ОБЖ» на 2022-2023 учебный год</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 29.08.2022 14:19:41 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a target="_blank" href="/about/sport/dokumenty/План спортивно-массовых мероприятий на 2022-2023 школьного спортивногоиклуба.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> План спортивно-массовых мероприятий на 2022-2023 школьного спортивного клуба «Метеор» на 2022-2023 учебный год</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 29.08.2022 11:05:33 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>

 <a href="/about/sport/dokumenty/Polozhenie_po_estofete.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о проведении спортивной эстафеты «А ну-ка, парни!» среди учеников 7-х и 8-х классов.</a><br>
 <a href="/about/sport/dokumenty/И1.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция по охране труда и мерам безопасности для учителя физкультуры</a> <br>
 <a href="/about/sport/dokumenty/инструкция по технике безопасности на открытых спортивных площадках.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция по охране труда для учащихся по мерам безопасности при занятиях на открытых спортивных площадках </a> <br>
 <a href="/about/sport/dokumenty/инструкция по технике безопасности в спортивном зале.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция по мерам безопасности для учащихся при занятиях в спортивном зале</a> <br>
 <a href="/about/sport/dokumenty/инструкция № 1 для учащихся по мерам безопасности при занятиях легкой атлетикой.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция для учащихся по мерам безопасности при занятиях легкой атлетикой</a> <br>
 <a href="/about/sport/dokumenty/инструкция № 2 для учащихся по мерам безопасности при занятиях спортивной гимнастикой.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция для учащихся по мерам безопасности при занятиях спортивной гимнастикой</a> <br>
 <a href="/about/sport/dokumenty/инструкция по технике безопасности при занятиях подвижными играми.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция для учащихся по мерам безопасности при занятиях подвижными играми</a> <br>
 <a href="/about/sport/dokumenty/инструкция № 3 для учащихся по мерам безопасности при занятиях спортивными играми (баскетбол,волейбол).pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция для учащихся по мерам безопасности при занятиях игровыми видами спорта (баскетбол, волейбол)</a> <br>
 <a href="/about/sport/dokumenty/инструкция по технике безопасности в раздевалках.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Инструкция по охране труда для учителя физической культуры в раздевалках спортивного зала</a> <br>
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>