<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Основное общее образование");
?><p style="text-align: justify;">
 <a target="_blank" href="/Gym40_information/obrazovanie/II-stupen/ООП ООО 2022.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Основная образовательная программа основного общего образования (ООП ООО)</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 30.08.2022 12:45:14 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a target="_blank" href="/Gym40_information/obrazovanie/II-stupen/ООП ООО_2022-2023 ФГОС 2010.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Основная образовательная программа основного общего образования (ООП ООО) (ФГОС – 2010)</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 30.08.2022 12:47:32 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/Gym40_information/obrazovanie/II-stupen/Учебный_план_ООО_2022-23уч.г. 5 кл..pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Учебный план основного общего образования (из «Организационного раздела» ООП ООО) для 5х классов</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2022 13:25:14 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/Gym40_information/obrazovanie/II-stupen/Учебный_план_ООО_2022-23уч.г. 6-9 кл..pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Учебный план основного общего образования (из «Организационного раздела» ООП ООО) для 6-9 классов</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2022 13:25:14 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/fgos/fgos-5-9/programmy/index.php"><i class="fa fa-external-link" aria-hidden="true"></i> Программы учебных предметов, курсов, модулей (приложение к «Содержательному разделу» ООП ООО)</a><br>
 <a href="/fgos/fgos-5-9/programmy-vd/index.php"><i class="fa fa-external-link" aria-hidden="true"></i> Программы курсов внеурочной деятельности (приложение к Организационному разделу» ООП ООО)</a><br>
 <a target="_blank" href="/Gym40_information/obrazovanie/II-stupen/годовой график ООО 2022-23_.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Календарный учебный график основного общего образования на 2022-2023 учебный год </a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2022 11:27:17 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a target="_blank" href="/Gym40_information/obrazovanie/II-stupen/АООП ООО с ЗПР, 2021г..pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Адаптированная основная общеобразовательная программа основного общего образования для обучающихся с задержкой психического развития</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 06.09.2021 11:10:55 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a target="_blank" href="/Gym40_information/obrazovanie/II-stupen/АООП ООО с НОДА, 2021г..pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Адаптированная основная общеобразовательная программа основного общего образования для обучающихся с нарушениями опорно двигательного аппарата</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 06.09.2021 11:10:32 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
</p>
<hr>
<p style="text-align: justify;">
 <a target="_blank" href="/Gym40_information/obrazovanie/II-stupen/ВД ООО 2021.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> План внеурочной деятельности (из "Организационного раздела" ООП ООО)</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2021 12:27:17 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/Gym40_information/obrazovanie/I-stupen/Календарный план ВР 2021-2022.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Календарный план воспитательной работы 2021 </a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 31.08.2021 14:28:47 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002">
</p>
<hr>
<p style="text-align: justify;">
 <a href="/fgos/fgos-5-9/oipd/oipd.php"><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i> Организация проектно-исследовательской деятельности</a>
</p>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>