<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Кафедра \"МИФ\"");
?><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Куратор предметного объединения:&nbsp;</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Абкадырова Римма Азатовна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%9A%D1%80%D0%B5%D1%87%D0%B5%D1%82%D0%BE%D0%B2%D0%B0.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;24 года</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Квалификация:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;первая&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Преподаваемые предметы, модули:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;математика</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"><br>
 <span style="color: #000000;">  </span></span></b><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Дополнительные сведения:&nbsp;</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"><span style="color: #000000;">
-работа в общеобразовательных классах, подготовка к итоговой аттестации. Результаты ЕГЭ по математике: 2014- средний балл 70, максимальный балл-94, призер заочного этапа олимпиады МГУ «Ломоносов»</span><br>
 <span style="color: #000000;">  </span></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Малая Алла Александровна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Malaya.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Учитель математики &nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> 25&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Квалификация:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> высшая&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">математика,</span><b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Решение многовариантных планиметрических задач, 9-ые и 11-ые классы</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> &nbsp;Факультатив «Решение олимпиадных задач», 9-ые классы</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Звания и награды:&nbsp;</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Грамота Министерства Образования и Науки РФ, 2015г.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> &nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: monospace;"><span style="font-family: Verdana; font-size: 10pt;"><b><span style="color: #000000;">Дополнительные&nbsp;сведения:</span></b></span></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Направления деятельности:</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> - эксперт по проверке ОГЭ и ЕГЭ;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> - эксперт по аттестации педагогических работников;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> - эксперт по проверке олимпиадных работ муниципального этапа ВОШ;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> - работа в профильных классах, подготовка к итоговой аттестации.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Результаты ЕГЭ:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> 2012 г. – 64,0 балла; 2014 г – 66, 2 балла; высший балл - 87; входной внешний мониторинг по физмат площадке:&nbsp;4,5 балл, 2015г.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Руководство исследовательской деятельностью учащихся</span></b><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">:</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> диплом 1 и 2 &nbsp;степени,&nbsp; г.Светлогорск,&nbsp; «Первые шаги в науке», 2016 г.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Участие в инновационных образовательных проектах</span></b><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">:</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> Проект развития физико-математического образования в КО – 2012-2017</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> Призеры и победители рейтинговых олимпиад и конкурсов:</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> Математическая регата, 1-3 места, 2015-17 гг;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> Победители и призеры Кантианы «Будущее с нами», 2015 гг;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> Победители муниципального этапа ВОШ олимпиады по математике – 2016, 2017 гг;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> 
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"><span style="color: #000000;">Региональный этап ВОШ по математике , 4 и 5 места. 2017 г.</span><br><span style="color: #000000;">  </span></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Медведькова Наталья Александровна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%9C%D0%B0%D0%BB%D0%B0%D1%8F.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Учитель информатики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> 29&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Квалификация:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> высшая,&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">информатика,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;робототехника 5-ые,6-ые классы</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp; &nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Дополнительные сведения:&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">- эксперт по проверке ОГЭ,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">- эксперт по аттестации педагогических работников,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Результаты экзаменов</span></b><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;2&nbsp; 100-бальника на ОГЭ 2015-2016 гг.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Участие в инновационных образовательных проектах</span></b><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">:</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Победители в конкурсах «КИТ» и «Инфознайка»,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Победители конкурсов по Робототехнике</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Семёновых&nbsp;Татьяна Игорьевна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Semenovich.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">&nbsp;Учитель информатик</span><br>
 <span style="color: #000000;">  </span></span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">&nbsp;12&nbsp;лет</span><br>
 <span style="color: #000000;">  </span></span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">информатика,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;элективный курс «3Dмоделирования» 7-9-ые&nbsp;классы,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">&nbsp;курс «Pascal» 7-8-ые классы</span><br>
 <span style="color: #000000;">  </span></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt;"><b><br>
 <span style="color: #000000;">  </span></b></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt;"><b><span style="color: #000000;">Дополнительные сведения:</span><br>
 <span style="color: #000000;">  </span></b></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">-&nbsp;</span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">работа в общеобразовательных и профильных классах</span><br>
 <span style="color: #000000;">  </span></span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">- внеурочная деятельность в 7-8 классах&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Березина Людмила Леоньтевна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Berezina.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> 19&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Квалификация:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> первая&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">математика</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp; &nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Дополнительные сведения:</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">- Работа в общеобразовательных и профильных классах, подготовка к итоговой аттестации</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Буткевич Ирина&nbsp;Геннадьевна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Butkevixk.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> 32&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Квалификация:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> высшая&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Преподаваемые предметы, модули:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> математика,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;«Математика. ЗФТШ.»,«Решение экономических задач»,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;«Решение задач повышенного уровня сложности»;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">  </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"><span style="color: #000000;">
&nbsp;Основы проектной и исследовательской деятельности учащихся</span><br>
 <span style="color: #000000;"> </span></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Звания и награды:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Звание «Старший учитель». 1989 г.,Звание «Учитель-методист».1990 г.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;Почётная грамота Управления образования администрации городского округа «Город Калининград» 2008 г.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
Почётная грамота Министерства Образования КО, 2013 г.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"><br>
 <span style="color: #000000;">
Дополнительные сведения:&nbsp;</span><br>
 <span style="color: #000000;"> </span></span></b><b><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">Направления деятельности:</span><br>
 <span style="color: #000000;"> </span></span></b><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- эксперт по проверке ОГЭ и ЕГЭ;</span><br>
 <span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- участник Федерального исследования компетенции учителей;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- участник регионального проекта развития физико-математического образования в КО – 2012-2017;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- эксперт по аттестации педагогических работников;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- эксперт по проверке олимпиадных работ муниципального этапа ВОШ;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- участник фестиваля педагогических идей «Открытый урок». г. Москва;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- участник фестиваля исследовательских и творческих работ, учащихся «Портфолио», г. Москва;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- организатор образовательного&nbsp;&nbsp;&nbsp; проекта «ЗФТШ МФТИ – ученикам»&nbsp; для одарённых&nbsp; детей;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- работа в профильных классах;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">-&nbsp; подготовка к итоговой аттестации;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- руководство исследовательской деятельностью учащихся: дипломы научно-практических конференций «Поиск и творчество»;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- участие в инновационных образовательных проектах;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- участник социального проекта «Обратная связь», организованного Союзом женщин России и Союзом женщин Калининградской области.</span><br><span style="color: #000000;"> </span></span><b><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">Обобщён педагогический опыт:</span><br>
 <span style="color: #000000;"> </span></span></b><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">в рамках региональной научно-практической конференции «Математическое образование: современные методики и инновации, опыт практического применения».2014 г.</span><br>
 <span style="color: #000000;"> </span></span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Результаты ЕГЭ:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> по математике: максимальный балл – 89.</span><i><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;"> (2014 г.)</span><br>
 <span style="color: #000000;"> </span></span></i><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Результаты ОГЭ:</span></b><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">
по математике: Два&nbsp; 100-бальника на ОГЭ (2015 г.)</span><br>
 <span style="color: #000000;"> </span></span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Призеры и победители рейтинговых олимпиад и конкурсов</span></b><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">:</span><br>
 <span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- Всероссийская олимпиада школьников по математике. 2015-2017 гг.&nbsp;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- победители и призёры муниципальных и региональных этапов;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- Региональный турнир физико-математического направления «Поиск. Творчество. Потенциал». 2014-2017 гг. – победители, призёры;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- Открытая региональная межпредметная олимпиада школьников Калининградской области «Эрудиты Балтики». 2012-2016 гг. &nbsp;– победители, призёры;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- Региональная олимпиада БФУ им. Канта «Будущее с нами».&nbsp; 2013-2015 – призёры;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- Общероссийская предметная олимпиадапо математике «Олимпус». 2013-2016 гг. - победители, призёры;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- Региональный конкурс «Математическая регата». 2013-2016 гг. – победители, призёры.- Межрегиональная олимпиада школьников по математике и криптографии – призёры 2014-2016 гг;</span><br><span style="color: #000000;"> 
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><span style="color: #000000;">- Олимпиада ФГБОУ ВО «КГТУ» по математике&nbsp;2017 г. – победитель, призёр</span><br></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Долгова Александра Анатольевна</span></b><span style="font-family: Verdana; font-size: 10pt;"><br>
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Dolgova.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Стаж работы:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> 20&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Квалификация:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> первая</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Преподаваемые предметы, модули:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> математика</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Звания и награды:&nbsp;</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Грамота Министерства Образования РФ, 2013 год</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp; &nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Дополнительная информация:</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000;"><span style="font-family: Verdana; font-size: 10pt;">
- работа в общеобразовательных и профильных классах, подготовка к итоговой аттестации</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Зикрач Юлия&nbsp;Сергеевна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%94%D0%BE%D0%BB%D0%B3%D0%BE%D0%B2%D0%B0.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Стаж работы:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;8&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Квалификация:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;первая&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Преподаваемые предметы, модули:&nbsp;</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">математика,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;«Решение задач на движение повышенного уровня сложности»</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Звания и награды:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;премия акима города Алматы 2015 год&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Дополнительные&nbsp;сведения: </span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">- работа в общеобразовательных и профильных классах.</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;">- внеурочная деятельность в 8 классах</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="color: #000000;"><span style="font-family: Verdana; font-size: 10pt;">- подготовка к итоговой аттестация в 9 классах </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span></span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Кудашкина Тамара Михайловна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%94%D0%BE%D0%BB%D0%B3%D0%BE%D0%B2%D0%B0.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;35&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Квалификация:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> высшая</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">математика,</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;&nbsp;</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;«Экономические задачи», «Решение задач повышенного уровня сложности»,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;основы проектной и исследовательской деятельности учащихся</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Звания и награды:&nbsp;</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Грамота Министерства Образования РФ,2000 г.,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
&nbsp;«Ветеран труда», 2000 г, «Почетный работник общего образования»,2015 г..</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Дополнительные сведения:&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">-Эксперт по проверке ОГЭ и ЕГЭ, эксперт по аттестации педагогических работников,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
-эксперт по аккредитации и лицензированию учебных заведений&nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Участие в инновационных образовательных проектах</span></b><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">:</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
15 медалистов среди выпускников 2015 года, победитель федерального конкурса «Умники России», 2016 год,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
призеры регионального конкурса «Математическая регата», «FOXFORD», «Олимпус»,2015-2017 года</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
  </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Малинская Елена&nbsp;Геннадьевна</span></b><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
  </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Malinskaya.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Стаж работы:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;27&nbsp;лет</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Квалификация:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> высшая&nbsp;</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 
&nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Преподаваемые предметы, модули: </span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">математика,&nbsp;</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 
&nbsp;«Текстовые задачи и техника их решения», «Математический калейдоскоп»,</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 
&nbsp;«Решение нестандартных задач по математике», «Практикум по решению рациональных неравенств».&nbsp;</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 
&nbsp;</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
  </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
  </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Дополнительные сведения:&nbsp;</span></b><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 
работа в профильных классах, подготовка к итоговой аттестации.</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
  </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Результаты ЕГЭ по математике 2016 г.:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> средний балл 70, максимальный балл- 86.</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Марков Николай Николаевич</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Markov.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 &nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Стаж работы:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;15&nbsp;лет</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Преподаваемые предметы, модули:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> математика</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 &nbsp;</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Дополнительные сведения:&nbsp;</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
</span><p style="display: inline !important;"><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
	 - работа в общеобразовательных и профильных классах, подготовка к итоговой аттестации</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
	 - преподаватель БФУ им.Канта курс «Актуарная математика», «Математические модели в промышленности»
</span></p><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span></b><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Новикова Дарья Александровна</span></b><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Novikova.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;Стаж работы:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;4&nbsp;года</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 &nbsp;</span><b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Преподаваемые предметы, модули:</span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">&nbsp;математика</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 Дополнительные сведения:</span><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">Руководство проектно- исследовательской деятельностью учащихся 8-х классов;</span><br><span style="color: #000000;"><span style="font-family: Verdana; font-size: 10pt;">
 Подготовка к итоговой аттестации в 9-х классах</span><br></span><br><b><span style="font-family: Verdana; font-size: 10pt;">Бекетов Юрий Александрович</span></b><br><a href=""><img width="131" src="/Gym40_information/administracija-2017/Beketov.jpg" height="150" align="left"></a><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Учитель информатики</span><br><span style="font-family: Verdana; font-size: 10pt;"> Заместитель директора по организации&nbsp; &nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;и внедрению информационных технологий</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt;">Стаж работы: 8 лет</span></b><br><b><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Квалификация: </span></b><span style="font-family: Verdana; font-size: 10pt;">первая</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt;">Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt;">информатика</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt;">Звания и награды:</span></b><span style="font-family: Verdana; font-size: 10pt;">Победитель муниципального этапа конкурса «Учитель
года-2015»,</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Победитель областного этапа конкурса «Учитель года-2015»,&nbsp;финалист всероссийского</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;этапа конкурса «Учитель года-2015»,&nbsp;Победитель конкурсного отбора лучших учителей РФ в рамках ПНПО.</span><br><br><span style="color: #000000; font-family: Verdana; font-size: 10pt;">
 </span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Филимонова Мария Николаевна</span></b><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
 </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%9D%D0%BE%D0%B2%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
 &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> 4&nbsp;года</span><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
 &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">математика,</span><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
 &nbsp;Создание сайтов в html</span><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
</span><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
</span><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
</span><br><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
</span><br><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;"><br></span></b><b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">Дополнительные сведения:&nbsp;</span><br></b><span style="font-family: Verdana; font-size: 10pt; color: #000000;">- работа в общеобразовательных и профильных классах<br></span><br><b><span style="font-family: Verdana; font-size: 10pt;">Филимонова Татьяна Юрьевна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/Filimonova.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><b><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt;">&nbsp;38&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt;">Квалификация:</span></b><span style="font-family: Verdana; font-size: 10pt;"> высшая&nbsp;</span><br><b><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Преподаваемые предметы, модули: </span></b><span style="font-family: Verdana; font-size: 10pt;">математика,</span><br><span style="font-family: Verdana; font-size: 10pt;">
 &nbsp;</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><b><span style="font-family: Verdana; font-size: 10pt;">Палий Алена Алексеевна</span></b><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%9D%D0%BE%D0%B2%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">
 &nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt;">Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt;">&nbsp;5&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><br><br><b><span style="font-family: Verdana; font-size: 10pt;">Шпаковская Светлана Александровна</span></b><br><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%9D%D0%BE%D0%B2%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt;">&nbsp;</span><br><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Стаж работы: 9&nbsp;лет</span><br><br><br><span style="font-family: Verdana; font-size: 10pt;">
 </span><br><br><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt;">Шестак Светлана Юрьевна</span></b><br><img width="131" src="http://gym40.ru/Gym40_information/administracija-2017/%D0%9D%D0%BE%D0%B2%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0.jpg" height="150" title="Рисунок: /Gym40_information/pedagogicheskiy-sostav-2017/Савинова.jpg" align="left"><span style="font-family: Verdana; font-size: 10pt;">&nbsp;Учитель математики и информатики</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;</span><b><span style="font-family: Verdana; font-size: 10pt;">Стаж работы:</span></b><span style="font-family: Verdana; font-size: 10pt;">&nbsp;9&nbsp;лет</span><br><span style="font-family: Verdana; font-size: 10pt;">&nbsp;</span><br><br><br><br><br><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>