<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Документы");
?><p style="text-align: justify; border-bottom: 2px solid black;">
 <span style="font-family: Verdana; font-size: 10pt;"><b>ДОКУМЕНТЫ</b></span>
</p>
<p style="text-align: justify;">
 <a href="/Gym40_information/documents/ustav.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Устав МАОУ Гимназии&nbsp;№40 им. Ю.А. Гагарина г. Калининграда</a><br>
 <a target="_blank" href="/Gym40_information/documents/izmeneniya_ustava_2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Изменения к уставу от 31 января 2017 г.</a>&nbsp;<br>
 <a href="/Gym40_information/documents/лицензия22032016.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Лицензия на осуществление образовательной деятельности (с приложениями)</a><br>
 <a href="/Gym40_information/documents/akkr2015.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Свидетельство о государственной аккредитации (с приложениями)</a><br>
 <a href="/Gym40_information/documents/Выписка из реестра лицензий № Л035-01236-39_00226990.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Выписка из реестра лицензий № Л035-01236-39_00226990 </a><br>
 <a href="/Gym40_information/fin-hoz/План ФХД на 21.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> План финансово-хозяйственной деятельности на 2021 год и плановый период 2022-2023 годов от 19.02.2021 г.</a><br>
 <a href="/Gym40_information/documents/Программа развития 21-25.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Программа развития гимназии 2021-2025 </a><br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> <a target="_blank" href="/Gym40_information/documents/Коллективный%20договор%202020-2022.pdf">Коллективный договор</a><br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> <a target="_blank" href="/Gym40_information/documents/Положение по оплате труда 2022 год( нов редакция).pdf">Положение об оплате труда и стимулировании работников гимназии </a> <img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 01.01.2022 13:10:58 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о правилах внутреннего распорядка обучающихся гимназии20.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о правилах внутреннего распорядка обучающихся</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Правила внутреннего распорядка работников.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Правила внутреннего распорядка работников</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/метод. рекомендации по обеспечению права на получение общего образования детей, прибывающих с территорий ДНР, ЛНР и Украины.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Методические рекомендации по обеспечению права на получение общего образования детей, прибывающих с территорий Донецкой Народной Республики, Луганской Народной Республики, Украины </a>
</p>
<p style="text-align: justify; border-bottom: 2px solid black;">
 <span style="font-family: Verdana; font-size: 10pt;"><b>ЛОКАЛЬНЫЕ НОРМАТИВНЫЕ АКТЫ</b></span>
</p>
<p style="text-align: justify;">
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/О внесении изменений в приказы.pdf"> Приказ № 704-о от 23.12.2022 "Об особенностях деятельности гимназии в период с 26 по 30 декабря 2022г. и о внесении изменений в приказы №№ 689-о, 393-о"</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 23.12.2022 17:11:22 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"> <br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a href="/Gym40_information/documents/Programma_vospitania_Gimnazia_40_Kaliningrad 2022-2025.pdf" target="_blank"> Программа воспитания</a> <br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Приказ о внесении изменений в План по ФГ.pdf"> Приказ № 20-о от 18.01.2022 "О внесении изменений в План мероприятий по формированию функциональной грамотности учащихся гимназии"</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 18.01.2022 15:11:22 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"> <br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Аналитическая справка по результатам ФГ-7.pdf"> Аналитическая справка по результатам проведения мониторингового исследования по оценке функциональной грамотности обучающихся 7-х классов МАОУ гимназии № 40 им. Ю. А. Гагарина в 2021-2022 учебном году</a> <br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Приказ о создании комиссии ППк 22-23.pdf"> Приказ "О создании психолого-педагогического консилиума на уровне НОО на 2022-2023 учебный год"</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 26.08.2022 12:11:46 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"> <br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Приказ о создании ППК на 2021-2022г..pdf"> Приказ "О создании психолого-педагогического консилиума на уровне ООО на 2021-2022 учебный год"</a> <img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 30.08.2021 12:21:02 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о деятельности ППК.pdf"> Положение о деятельности психолого-педагогического консилиума</a><br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о системе оцениваниия_2021г..pdf"> Положение о системе оценивания, формах, периодичности, порядке текущего контроля успеваемости и промежуточной аттестации обучающихся&nbsp;</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 30.08.2021 13:11:45 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/incoming/perevod/положение о зачислении обуч в МАОУ гимн 40 в порядке перевода из др ОО.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о зачислении обучающихся в гимназию в порядке перевода из другой образовательной организации</a> <br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/incoming/10_class_incoming/Положение о классах с углубленным изучением предметов_2022.pdf"> Положение о классах с углублённым изучением предметов МАОУ гимназии №40 им. Ю. А. Гагарина </a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 08.06.2022 13:20:06 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"> <br>
 <a href="/incoming/1_class_incoming/pravila_priema_1_klass" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Правила приема в первые классы</a> <br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение%20о%20единых%20требованиях%20к%20одежде%20учащихся.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о единых требованиях к одежде учащихся</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Регламент предоставления услуги Электронный журнал.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Регламент предоставления услуги «Электронный журнал»</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о ведении электронного классного журнала.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о ведении электронного классного журнала</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о рабочих программах_2018.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о рабочих программах</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о режиме занятий обучающихся 2017.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о режиме занятий обучающихся</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Порядок индивид. учета результатов 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок осуществления индивидуального учёта результатов освоения обучающимися образовательных программ и хранения в архивах информации об этих результатах на бумажных и (или) электронных носителях</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Порядок зачета результатов освоения учащимися учебных предметов 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок зачета результатов освоения учащимися учебных предметов, курсов, дисциплин (модулей), дополнительных образовательных программ в других организациях, осуществляющих образовательную деятельность</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/О формах получения образования 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о формах получения образования, об обучении по индивидуальному учебному плану и ускоренном обучении</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение об использовании цифровых образовательных ресурсов в гимназии.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об использовании цифровых образовательных ресурсов</a><br>
 <a href="/Gym40_information/documents/lokalnye/совет по профилактике.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение Совета по профилактике асоциальных явлений</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о наблюдательном совете.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о Наблюдательном совете</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о педагогическом совете.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о Педагогическом совете</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о родит конференции.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о родительской конференции</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о родительском комитете класса20.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о родительском комитете класса</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение_о_родительском_Совете_новое.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о Родительском совете</a><br>

 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Правила этики цифрового общения.pdf"> Положение об этике общения в родительских чатах в социальных сетях и мессенджерах</a> <img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 16.01.2023 12:21:02 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>


 <a href="/Gym40_information/documents/lokalnye/положение о стк.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о Совете трудового коллектива</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о собрании работников.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о Собрании работников</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о сайте.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об информационном сайте</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о противодействии коррупции.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о мерах по предупреждению и противодействию коррупции</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение_ОВЗ.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об организации обучения лиц с ограниченными возможностями здоровья</a><br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/положение о библиотеке гимназии.pdf"> Положение о библиотеке в МАОУ гимназии № 40 им. Ю.А. Гагарина</a> <img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 01.09.2022 12:21:02 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <a href="/Gym40_information/documents/lokalnye/ДОГОВОР ПОЖЕРТВОВАНИЯ.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Договор пожертвования</a><br>
 <a href="/Gym40_information/documents/lokalnye/правила для спорт площадки.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Правила использования спортплощадки (стадиона)</a><br>
 <a href="/Gym40_information/documents/lokalnye/Правила учета, выдачи и хранения аттестатов.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Правила учета, выдачи и хранения аттестатов</a><br>
 <a href="/Gym40_information/documents/lokalnye/Приказ о создании комиссии по предупреждению конфликтов20.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Приказ о создании комиссии по предупреждению конфликтов</a><br>
 <a href="/Gym40_information/documents/lokalnye/224-о.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Приказ об организации образовательного процесса в 2020-2021 учебном году</a> <br>
 <a href="/Gym40_information/documents/lokalnye/Регламент 2020.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Регламент работы в соответствии с новыми требованиями к организации образовательного процесса в условиях сохранения рисков распространения COVID-19</a><br>
 <a href="/Gym40_information/documents/lokalnye/Порядок оформления отношения между ОО и обучающимися.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок оформления возникновения, приостановления и прекращения отношений между гимназией и обучающимися и (или) их родителями (договор) </a> <br>
 <a href="/Gym40_information/documents/lokalnye/429_о.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Об усилении мер по профилактике короновирусной инфекции (COVID-19)</a> <br>
 <a href="/Gym40_information/documents/lokalnye/Приказ об организации занятий 16-30 ноября 2020.PDF" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Приказ об организации образовательного процесса 16-30 ноября 2020г.</a><br>
 <a href="/Gym40_information/documents/lokalnye/график впр осень 2022.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> График проведения ВПР в 5-9х классах в 2022г.</a> <br>
 <a href="/Gym40_information/documents/lokalnye/порядок впр 2022.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок проведения ВПР </a>
</p>
<p style="text-align: justify; border-bottom: 2px solid black;">
 <span style="font-family: Verdana; font-size: 10pt;"><b>ОТЧЁТ О РЕЗУЛЬТАТАХ САМООБСЛЕДОВАНИЯ</b></span>
</p>
<p style="text-align: justify;">
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> <a href="/Gym40_information/documents/Самообследование 21.pdf" target="_blank">Отчёт по итогам самообследования деятельности МАОУ гимназии №40 им. Ю.А. Гагарина в 2020-2021 учебном году</a><img src="/Gym40_information/documents/icon_pod.png" align="" style="width: 2%;" title="Документ подписан электронной подписью Дата и время подписания: 15.05.2021 14:11:45 Документ подписал: директор Мишуровская Т.П. Сформированный уникальный программный ключ: 01d703aaacece950000000c900060002"><br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> <a href="/Gym40_information/documents/Отчет%20самообследование%202020.pdf" target="_blank">Отчёт по итогам самообследования деятельности МАОУ гимназии №40 им. Ю.А. Гагарина в 2019-2020 учебном году</a><br>
 <a href="/Gym40_information/documents/Отчёт самообследования 2019 год.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Отчёт по итогам самообследования деятельности МАОУ гимназии №40 им. Ю.А. Гагарина в 2018-2019 учебном году</a><br>
 <a href="/Gym40_information/documents/Самообследование 2018год.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Отчёт по итогам самообследования деятельности МАОУ гимназии №40 им. Ю.А. Гагарина в 2017-2018 учебном году</a><br>
 <a href="/Gym40_information/documents/Результаты самообследования.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Отчёт по итогам самообследования деятельности МАОУ гимназии №40 им. Ю.А. Гагарина в 2016-2017 учебном году</a><br>
 <a target="_blank" href="/Gym40_information/documents/самообследование2015_2016.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Отчёт по итогам самообследования деятельности МАОУ гимназии №40 им. Ю.А. Гагарина в 2015-2016 учебном году</a><br>
 <a href="/Gym40_information/documents/arkhiv/samoobsledovanie.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Отчёт по итогам самообследования деятельности МАОУ гимназии №40 им. Ю.А. Гагарина в 2014-2015 учебном году</a><br>
</p>
<p style="text-align: justify; border-bottom: 2px solid black;">
 <span style="font-family: Verdana; font-size: 10pt;"><b>ПОРЯДОК ОКАЗАНИЯ ПЛАТНЫХ УСЛУГ</b></span>
</p>
<p style="text-align: justify;">
 <a target="_blank" href="/Gym40_information/platnye-uslugi/Положение о платных услугах 2021.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об оказании платных дополнительных образовательных услуг в МАОУ гимназии №40 им. Ю.А. Гагарина</a><br>
 <a target="_blank" href="/Gym40_information/platnye-uslugi/Реестр цен 19-20.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Реестр цен на оказание дополнительных платных и иных видов услуг</a><br>
 <a target="_blank" href="/Gym40_information/platnye-uslugi/Договор на оказание платных образовательных услуг ( Подготовка в к школе) .docx"><i class="fa fa-file-word-o fa-lg" aria-hidden="true"></i> Договор об оказании платных услуг (подготовка к школе, рисование и тд.)</a> <br>
 <a target="_blank" href="/Gym40_information/platnye-uslugi/договор на оказание платных образовательных услуг (Обучение плаванию) ..docx"><i class="fa fa-file-word-o fa-lg" aria-hidden="true"></i> Договор об оказании платных услуг (обучение плаванию)</a> <br>
 <a target="_blank" href="/Gym40_information/platnye-uslugi/Договор на оказание платных образовательных услуг ( Радуга Открытия).docx"><i class="fa fa-file-word-o fa-lg" aria-hidden="true"></i> Договор об оказании платных услуг (Радуга Открытия)</a> <br>
</p>
 <!--
<p style="text-align: justify; border-bottom: 2px solid black;">
 <span style="font-family: Verdana; font-size: 10pt;"><b>ПУБЛИЧНЫЙ ОТЧЁТ ДИРЕКТОРА</b></span>
</p>
<p style="text-align: justify;">
 <a target="_blank" href="/Gym40_information/publichnyy-doklad-direktora/Публичный доклад-2019г.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Публичный отчёт директора за 2018-2019 учебный год</a> <br>
 <a target="_blank" href="/Gym40_information/publichnyy-doklad-direktora/Публичный отчет 2017-2018 уч.год.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Публичный отчёт директора за 2017-2018 учебный год</a><br>
 <a target="_blank" href="/Gym40_information/publichnyy-doklad-direktora/Публичный доклад директора 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Публичный отчёт директора за 2016-2017 учебный год</a>
</p>
-->
<p style="text-align: justify; border-bottom: 2px solid black;">
 <span style="font-family: Verdana; font-size: 10pt;"><b>ПРЕДПИСАНИЯ ОРГАНОВ, ОСУЩЕСТВЛЯЮЩИХ ГОСУДАРСТВЕННЫЙ КОНТРОЛЬ</b></span>
</p>
<p style="text-align: justify;">
 <a href="/Gym40_information/documents/санит_эпид_заключение.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Санитарно-эпидемиологическое заключение</a><br>
 <a href="/Gym40_information/documents/заключение_пож.jpg" target="_blank"><i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i> Заключение о соответствии требованиям пожарной безопасности</a><br>
 <br>
	 Проверка проводилась Службой по контролю и надзору в сфере образования Калининградской области в соответствии с приказом №1417 от 20.09.2013 г. «О проведении документарной проверки». <br>
	 Согласно акту проверки № 628/05 от 02 октября 2013 г. <b>нарушений не выявлено.</b>
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>