<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Локальные");
?><p style="text-align: justify;">
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Приказ_ПМПК.pdf">Приказ "О создание психолого-медико-педагогического консилиума на уровне НОО на 2019-2020 учебный год"</a>
<br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Приказ_ПМПК_ООО.jpg">Приказ "О создании ПМПК гимназии на ступени ООО на 2019-2020 учебный год"</a>
<br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о ПМПК гимназии.pdf">Положение "О деятельности психолого-медико-педагогического консилиума в МАОУ гимназии №40 им. Ю.А.Гагарина"</a><br>
 <i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i><a target="_blank" href="/Gym40_information/documents/lokalnye/Положение%20о%20классах%20с%20углубленным%20изучением%20предметов.pdf">Положение о классах с углублённым изучением предметов</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение%20о%20единых%20требованиях%20к%20одежде%20учащихся.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i>Положение о единых требованиях к одежде учащихся</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Регламент предоставления услуги Электронный журнал.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Регламент предоставления услуги «Электронный журнал»</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о ведении Электронного журнала.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о ведении электронного классного журнала</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о рабочих программах_2018.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о рабочих программах</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о режиме занятий обучающихся 2017.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о режиме занятий обучающихся</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Порядок индивид. учета результатов 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок осуществления индивидуального учёта результатов освоения обучающимися образовательных программ и хранения в архивах информации об этих результатах на бумажных и (или) электронных носителях (новая редакция)</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Порядок зачета результатов освоения учащимися учебных предметов 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Порядок зачета результатов освоения учащимися учебных предметов, курсов, дисциплин (модулей), дополнительных образовательных программ в других организациях, осуществляющих образовательную деятельность</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/О формах получения образования 2017.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о формах получения образования, об обучении по индивидуальному учебному плану и ускоренном обучении (новая редакция)</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение о правилах внутреннего распорядка 17.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о правилах внутреннего распорядка обучающихся (новая редакция)</a><br>
 <a target="_blank" href="/Gym40_information/documents/lokalnye/Положение об использовании цифровых образовательных ресурсов в гимназии.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об использовании цифровых образовательных ресурсов</a><br>
 <a target="_blank" href="http://gym40.ru/Gym40_information/obrazovanie/metod-dokumenty/Положение_о_системе_оцениваниия.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о формах, периодичности и порядке текущего контроля успеваемости и промежуточной аттестации учащихся</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о совете по профилактике асоц явлений.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение Совета по профилактике асоциальных явлений</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение об администрат совете.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об административном совете</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о наблюдательном совете.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о наблюдательном совете</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение о педагогическом совете.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о педагогическом совете</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о родит конференции.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о родительской конференции</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о родит комитете класса.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о родительском комитете класса</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение_о_родительском_Совете_новое.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о родительском Совете (в новой редакции)</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о стк.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о Совете трудового коллектива</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о собрании работников.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о собрании работников</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о сайте.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об информационном сайте</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о противодействии коррупции.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о мерах по предупреждению и противодействию коррупции</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение о структ подразделении.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о структурном подразделении гимназии</a><br>
 <a href="/Gym40_information/documents/lokalnye/Положение_ОВЗ.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение об организации обучения лиц с ограниченными возможностями здоровья</a><br>
 <a href="/Gym40_information/documents/lokalnye/положение добровольные пожертвования.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Положение о порядке привлечения, расходования и учета безвозмездных поступлений</a><br>
 <a href="/Gym40_information/documents/lokalnye/ДОГОВОР ПОЖЕРТВОВАНИЯ.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Договор пожертвования</a><br>
 <a href="/Gym40_information/documents/lokalnye/правила для спорт площадки.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Правила использования спортплощадки (стадиона)</a><br>
 <a href="/Gym40_information/documents/lokalnye/Правила учета, выдачи и хранения аттестатов.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Правила учета, выдачи и хранения аттестатов</a><br>
 <a href="/parents/Комиссия по предупреждению конфликтов.PDF"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Приказ о создании Комиссии по предупреждению конфликтов</a><br>
 <a href="/Gym40_information/documents/lokalnye/муниципальное задание на 2019 год и плановый период 2020-2021.pdf"><i class="fa fa-file-pdf-o fa-lg text-pdf" aria-hidden="true"></i> Муниципальное задание на 2019 год и плановый период 2019-2020</a>
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>