<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Кафедра \"МИФ\"");
?><p style="text-align: justify;">
 <span style="font-family: Verdana;"><span style="color: #000000; font-size: 10pt;">&nbsp;Современное образование призвано решать различные задачи и проблемы современности, в первую очередь, проблемы социализации и адаптации учащихся. Сейчас определен результат обучения ребенка в школе – формирование ключевых компетенций. В соответствии с требованием ФГОС ООО/ СОО (IV.п.21) кафедра МИФ призвана «обеспечивать возможность развития личности, способностей, удовлетворения познавательных интересов, самореализации обучающихся, в том числе одаренных и талантливых».&nbsp;</span> <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-size: 10pt;"> </span><img width="453" src="/Gym40_information/kafedry/kafedra-mif/documents/ScrollsIII.png" height="130" align="right"><span style="color: #000000; font-size: 10pt;"> </span></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><i><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span></i></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><i><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span></i></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><i><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span></i></b><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><b><i><span style="font-family: Verdana; color: #000000;"><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	Работа кафедры по сопровождению учащихся строится по следующим направлениям:</span></span></i></b><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;">
	- </span><i><span style="font-family: Verdana; color: #000000; font-size: 10pt;">Создание современной учебно-материальной базы для обучения</span></i><span style="font-family: Verdana; color: #000000; font-size: 10pt;">. Обеспечение учебниками по физике, математике, информатике учащихся 7-9 классов, обучающимися по ФГОС ООО и учащихся 10-11 классов, обучающимися по ФГОС СОО. Создание и оснащение Физико- технического центра гимназии «Клен». Поставка лабораторного и демонстрационного оборудования по физике. Поставка компьютерного оборудования и оргтехники (ноутбуки, документ-камера, видеокамера, 3D-принтер, система голосования, интерактивная доска, интерактивные планшеты). Поставка программных продуктов по физике, математике, информатике. </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana;"><span style="color: #000000; font-size: 10pt;"> </span><a href=""><img width="200" src="/Gym40_information/kafedry/kafedra-mif/documents/рис.2 фото.JPG" height="150" align="right"></a><span style="color: #000000; font-size: 10pt;">- На базе </span></span><i><span style="font-family: Verdana; color: #000000; font-size: 10pt;">Физико-технического центра гимназии «Клен»</span></i><span style="font-family: Verdana; color: #000000;"><span style="font-size: 10pt; color: #000000;"> организованы различные формы урочной и внеурочной работы. Это деятельность клубных объединений обучающихся:<br>
 </span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	- «Юный физик», «Юный астроном», «Научное общество учащихся» и др.;<br>
 </span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	- Организация мероприятий для учащихся в рамках </span></span><i><span style="font-family: Verdana; color: #000000; font-size: 10pt;">профильных физ-мат дней</span></i><span style="color: #000000;"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">, предметных и межпредметных интегрированных проектов по плану развития гимназии: «Механистическая картина мира», «Уроки Гагарина» и др.;<br>
 <br>
 </span><span style="color: #000000;"><span style="font-size: 10pt; font-family: Verdana;">- Для родителей обучающихся в рамках гимназического проекта «ЛАД» и Форума педагогической, родительской, ученической общественности;</span><br>
 </span></span><span style="font-family: Verdana; font-size: 10pt;"><br>
 <span style="color: #000000;">- Для представителей ОУ Калининграда, регионов РФ, зарубежных гостей и представителей общественности. Эти мероприятия позволяют гимназистам расширить сферу общения, почувствовать себя хозяевами и соорганизаторами мероприятий.</span></span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="font-family: Verdana; color: #000000; font-size: 10pt;">&nbsp;<i>Разработка программ профильного обучения</i></span><span style="font-family: Verdana; color: #000000; font-size: 10pt;">&nbsp; учащихся 5-11 классов по математике, 7-11 по физике и информатике в соответствии с требованием ФГОС ООО/ СОО. Неотъемлемой частью рабочей программы профильного обучения&nbsp; является </span><i><span style="font-family: Verdana; color: #000000; font-size: 10pt;">внутрипредметный модуль</span></i><span><span style="font-family: Verdana; color: #000000; font-size: 10pt;">, призванный расширить границы восприятия обучающихся. Это инновация в предметной области «физика»: «Лабораторный практикум по физике»- в классах, изучающих физику на профильном и на базовом уровне. Внутрипредметный модуль по математике рассчитан на учащихся 8-х профильных классов «Решение задач на движение повышенного уровня сложности», для 9-х и 11-х профильных классов предлагается к изучению модуль «Решение многовариативных задач по планиметрии». А в 7 профильном классе изучают «Алгоритмику и программирование» в рамках внутрипредметного модуля по информатике.</span><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana;"><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/УМК, рабочие программы.pdf"><span style="color: #000000; font-size: 10pt;">УМК, рабочие программы</span></a></span><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt;"><a href="/Gym40_information/kafedry/kafedra-mif/documents/рис.4 фото.JPG" target="_blank"><img width="100" src="/Gym40_information/kafedry/kafedra-mif/documents/рис.4 фото.JPG" height="150" align="left"></a></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: Verdana; color: #000000;"><span style="font-size: 10pt; color: #000000;">&nbsp;Инновационный проект 2016-2017 года «Дни физ-мат профиля» подкреплён актуальными рабочими программами занятий профильного дня в гимназических классах с углубленным изучением физики, математики, информатики, а также межпредметных модулей физ-мат направления: «Решение нестандартных задач по математике», «Практикум по решению рациональных неравенств», «Решение сложных задач планиметрии», «3D моделирование в различных средах», «Решение изобретательских задач», «Решение нестандартных задач по&nbsp; физике», «Компьютерное моделирование физических процессов в графической среде GeoGebra»,&nbsp; «Математические методы физики».</span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	&nbsp;В программах профильного дня заложены часы на интегрированные проекты и лабораторный практикум. Осуществляются масштабные проекты кафедры МИФ, в которых задействованы учащихся 7,8,10 классов физико- математического и экономического профиля: интегрированный проект «Механистическая картина мира»; «Фестиваль науки» поддержали все предметные объединения; «Нобелевские чтения» 7-10 классы всех профильных направлений гимназии, масштабный проект «Путь к звёздам». В рамках профильных дней реализуется идея социального партнёрства гимназии с Инновационным технопарком «Кванториум» БФУ им. И. Канта. В практикуме на базе технопарка принимают участие 7,8,10 классы физико-математического профиля.&nbsp;</span></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: Verdana;"><span style="color: #000000; font-size: 10pt;">&nbsp;Результаты проектной деятельности по профилю учащиеся отражают в Дневнике проектной деятельности, в котором предусмотрен специальный вкладыш для детального отражения проекта «Кванториум»&nbsp;</span><br>
 <span style="color: #000000;"> </span><span style="color: #000000; font-size: 10pt;"> </span><br>
 <span style="color: #000000;"> </span><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Кванториум. Вкладыш в дневник проектной деятельности .pdf"><span style="color: #000000; font-size: 10pt;">«Кванториум», вкладыш в дневник проектной деятельности</span></a></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana;"><span style="color: #000000; font-size: 10pt;"> </span><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Кванториум. Вкладыш в дневник проектной деятельности .pdf"><span style="color: #000000; font-size: 10pt;"> </span></a></span><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Кванториум. Вкладыш в дневник проектной деятельности .pdf"><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span></a><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Кванториум. Вкладыш в дневник проектной деятельности .pdf"><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span></a><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;">&nbsp;В рамках программы сопровождения организованы внеурочные занятия с одарёнными учащимися, готовящимся к участию в олимпиадах и конкурсах различного уровня, испытывающими потребности в развитии умения решать задачи высокого уровня по математике и физике, информатике и программированию. Проводятся внеурочные занятия по подготовке к ГИА. Программы курса внеурочной деятельности «Математический калейдоскоп»; «За страницами учебника математики», «Экономические задачи в КИМ ЕГЭ», «Решение олимпиадных задач», «Практикум по решению конкурсных задач по физике», «Информатика в экономике», «3D моделирование», «Pascal» и др. </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: Verdana;"><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Программы курсов сопровождения обучающихся.pdf"><span style="color: #000000; font-size: 10pt;">Программы курсов сопровождения обучающихся</span></a></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt;"><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Программы курсов сопровождения обучающихся.pdf"></a></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p class="" style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: Verdana; color: #000000;"><span style="font-size: 10pt; color: #000000;">&nbsp;Мероприятия для учащихся классов физико-математического профиля в рамках сетевого партнёрства школ - участников регионального проекта «Реализация концепции развития математического образования в Калининградской области». Это, прежде всего, конкурсы -&nbsp; предметные, межпредметные на базе школ- площадок по физ-мат направлению; мероприятия регионального уровня на базе гимназии (конкурс «Парад планет» - в рамках развития лингвистического образования и физмат-площадки, Фестиваль науки и творчества).</span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	&nbsp;Участие в системе региональных мероприятий: Городской фестиваль науки на базе Музея мирового океана, Инженерные соревнования на базе ФТИ БФУ им. И.Канта, Всероссийский &nbsp;синхронный чемпионат по интеллектуальным играм среди школьников «Формула интеллекта» на базе Центра по атомной энергии. Интеллектуальные конкурсы Российского и регионального уровня: «ЧИП», «ЭРУДИТЫ БАЛТИКИ», «ЛЕОНАРДО» и т.д.</span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span></span><span style="font-family: Verdana;"><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	&nbsp;Важное место занимают дистанционные и заочные формы участия обучающихся в конкурсных мероприятиях по профильным дисциплинам: интернет-олимпиады: Онлайн олимпиада Физтех, Международная онлайн- олимпиада «Фоксфорд», «Науки будущего», «Плюс 5», «Высшая проба»;&nbsp; интернет-конкурсы: «Твое призвание финансист», «Умники России», «Эксперимент-двигатель науки»;&nbsp; интернет-проекты: «Удивительный мир физики», Вдохновение»; &nbsp;детский клуб физиков (дистанционная форма), физико-техническая школа МФТИ.&nbsp; </span></span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/результативность участия в олимпиадах, конкурсах, конференциях.pdf"><span style="font-family: Verdana; color: #000000; font-size: 10pt;">Результативность участия в олимпиадах и конкурсах</span></a><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p class="MsoNormal">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p class="MsoNormal" style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;">- </span><i><span style="font-family: Verdana; color: #000000; font-size: 10pt;">Организация индивидуальной исследовательской и проектной деятельности</span></i><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p class="MsoNormal" style="text-align:justify">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> Индивидуальная исследовательская и проектная деятельность - это один&nbsp; из&nbsp; подходов&nbsp; решения&nbsp; задачи&nbsp; развития&nbsp; креативности&nbsp; учащихся.<br>
 </span><br>
 <b><span style="color: #000000; font-family: Verdana; font-size: 10pt;">В&nbsp; качестве&nbsp; таковых&nbsp; обязательных&nbsp; компонентов выделяются:<br>
 </span></b><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana;"><span style="color: #000000; font-size: 10pt;">-&nbsp;деятельность&nbsp; учителя&nbsp; по&nbsp; отбору&nbsp; творческих&nbsp; заданий,&nbsp; исследовательских,&nbsp;&nbsp; конструктивно-моделирующих&nbsp; заданий&nbsp; и&nbsp; т.д.&nbsp; (обеспечивается этап&nbsp; применения&nbsp; и&nbsp; самостоятельного&nbsp; получения&nbsp; знаний);</span><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-size: 10pt;"> </span></span><span style="font-family: Verdana;"><span style="color: #000000;"><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	-&nbsp;деятельность&nbsp; учителя&nbsp; по&nbsp; отбору&nbsp; и&nbsp; формированию&nbsp; у&nbsp; учащихся&nbsp; креативных&nbsp; методов&nbsp; и&nbsp; эвристических&nbsp; приемов&nbsp; решения&nbsp; задач,&nbsp; индивидуальны креативных стратегий&nbsp; деятельности,&nbsp; активизирующих творческие процессы мышления (этап&nbsp; закрепления&nbsp; и&nbsp; применения&nbsp; знаний);</span></span><br>
 <span style="color: #000000;"> </span><span style="color: #000000; font-size: 10pt;"> </span></span><span style="font-family: Verdana;"><span style="color: #000000;"><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	-&nbsp;деятельность&nbsp; учителя&nbsp; по&nbsp; систематизации,&nbsp; структурированию,&nbsp; визуализации&nbsp; знаний&nbsp; и&nbsp; субъектного&nbsp; опыта&nbsp; учащихся,&nbsp; формированию&nbsp; их&nbsp; креативного&nbsp; потенциала&nbsp; (этап&nbsp; объяснения&nbsp; учебного&nbsp; материала,&nbsp; закрепления,&nbsp; контроля).</span></span><br>
 <span style="color: #000000;"> </span><span style="color: #000000; font-size: 10pt;"> </span></span><span style="font-family: Verdana; color: #000000;"><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	- для популяризации научных знаний в сфере физико-математического образования и развития интеллектуального творчества учащихся осуществляются интеллектуальные и творческие проекты гимназического, &nbsp;регионального и всероссийского уровня: ведётся страница «События МИФ» на сайте гимназии, публикуются материалы в гимназическом журнале «Сорока», издаются&nbsp; печатные альманахи «Живая наука», «Научный калейдоскоп», ведётся съемка видеосюжетов.&nbsp;</span></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p class="MsoNormal" style="text-align:justify">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: Verdana;"><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/дневник проектной деятельности физ-мат.pdf"><span style="color: #000000; font-size: 10pt;">Дневник проектной деятельности&nbsp;учащихся физико-математический классов</span></a></span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;">- </span><i><span style="font-family: Verdana; color: #000000; font-size: 10pt;">Совершенствование системы оценки результативности работы с одарёнными детьми</span></i><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; color: #000000; font-size: 10pt;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-family: Verdana; font-size: 10pt;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"><span style="font-family: Verdana; font-size: 10pt; color: #000000;">&nbsp;Приоритетным в ученической среде становится принцип интеллектуального сотворчества. Всё более явной становится тенденция&nbsp; к созданию разновозрастного сообщества учеников, увлечённых изучением физико-математических дисциплин и компьютерных технологий. Более старшие гимназисты выходят в классы младших параллелей с лекциями, презентацией проектов, разрабатывают и проводят интеллектуальные конкурсы, занятия в планетарии, учат пользоваться современным оборудованием.</span><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;">
	&nbsp;Младшие гимназисты, становятся сначала активными участниками проводимых старшими гимназистами мастерских, интерактивных занятий, затем берут на себя роль соорганизаторов подобных мероприятий. Таким образом организованная работа способствует достижению устойчиво положительных личностных и метапредметных результатов освоения образовательной программы по предметам физико-математического направления.&nbsp;</span><br>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span></span><span style="font-family: Verdana;"><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;">
	&nbsp;Налажен процесс отражения в гимназических СМИ вопросов физико-математического образования в гимназии. В журнале «Сорока» медиахолдинг гимназии регулярно размещает информацию о мероприятиях кафедры математики, физики и информатики (МИФ), ведётся постоянная научная рубрика. Творческими группами учеников и учителей физики выпускается альманах «Естественно-научный калейдоскоп», «Академия естественных наук», научно-познавательная газета «Живая наука» (приложения к журналу «Сорока»). &nbsp;На сайте гимназии (гимназия40.рф) размещается информация по физико-математическому образованию, размещаются очередные выпуски приложений к «Сороке». Проводятся совместные акции с информационно - библиотечным центром гимназии. В рамках прикладных проектов «Международная молодёжная ассамблея», «Школа юных дипломатов», «Медиахолдинг гимназии № 40» делается акцент на&nbsp; оценку &nbsp;личностных и метапредметных результатов обучающихся.</span></span><span style="font-family: Verdana; font-size: 10pt;"><br>
 <span style="color: #000000;"> </span></span><span style="font-family: Verdana; font-size: 10pt;"><br>
 <span style="color: #000000;"> </span></span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
</p>
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="color: #000000;"> </span>
<p style="text-align: justify;">
 <span style="color: #000000;"> </span><span style="font-family: Verdana; font-size: 10pt; color: #000000;"> </span><span style="font-family: Verdana;"><span style="color: #000000; font-size: 10pt;"> </span><br>
 <span style="color: #000000;"> </span><span style="color: #000000;"><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Публикации педагогов, учащихся.pdf"><span style="color: #000000; font-size: 10pt;">Публикации&nbsp;педагогов и учащихся</span></a><br>
 <span style="color: #000000;"> </span><span style="font-size: 10pt; color: #000000;"> </span><span style="color: #000000; font-size: 10pt;"> </span></span><span style="color: #000000;"><a target="_blank" href="/Gym40_information/kafedry/kafedra-mif/documents/Сорока-репортаж о Кванториуме.pdf"><span style="color: #000000; font-size: 10pt;">Репортаж газеты "Сорока"</span></a></span></span>
</p>
<p>
</p>
<p class="MsoNormal">
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>